import { CareerRecommendation, JobOpportunity, RoadmapMilestone, ProgressAnalytics } from '@/types/career';

export const aptitudeQuestions = [
  {
    id: 'q1',
    category: 'analytical' as const,
    question: 'I enjoy solving complex puzzles and logical problems.',
  },
  {
    id: 'q2',
    category: 'technical' as const,
    question: 'I can understand code snippets quickly, even in unfamiliar languages.',
  },
  {
    id: 'q3',
    category: 'communication' as const,
    question: 'I can explain technical ideas clearly to non-technical people.',
  },
  {
    id: 'q4',
    category: 'leadership' as const,
    question: 'I naturally take charge in group settings and enjoy guiding others.',
  },
  {
    id: 'q5',
    category: 'creative' as const,
    question: 'I often come up with unique ideas and innovative solutions.',
  },
  {
    id: 'q6',
    category: 'collaboration' as const,
    question: 'I enjoy pair programming or team-based problem solving.',
  },
  {
    id: 'q7',
    category: 'adaptability' as const,
    question: 'I adapt quickly when project requirements suddenly change.',
  },
  {
    id: 'q8',
    category: 'business' as const,
    question: 'I think about user value and market impact while building features.',
  },
  {
    id: 'q9',
    category: 'analytical' as const,
    question: 'I prefer making decisions based on data rather than intuition.',
  },
  {
    id: 'q10',
    category: 'technical' as const,
    question: 'I enjoy debugging difficult issues until root cause is found.',
  },
  {
    id: 'q11',
    category: 'communication' as const,
    question: 'I am confident while presenting to a class, mentor, or interviewer.',
  },
  {
    id: 'q12',
    category: 'leadership' as const,
    question: 'I can split a large goal into tasks and coordinate people to finish it.',
  },
  {
    id: 'q13',
    category: 'creative' as const,
    question: 'I enjoy designing UI flows, prototypes, or product experiences.',
  },
  {
    id: 'q14',
    category: 'collaboration' as const,
    question: 'I actively seek feedback and improve based on teammates suggestions.',
  },
  {
    id: 'q15',
    category: 'adaptability' as const,
    question: 'I learn new frameworks/tools fast when needed for a project.',
  },
  {
    id: 'q16',
    category: 'business' as const,
    question: 'I can prioritize tasks based on effort vs impact.',
  },
  {
    id: 'q17',
    category: 'analytical' as const,
    question: 'I like identifying patterns from raw data before making decisions.',
  },
  {
    id: 'q18',
    category: 'technical' as const,
    question: 'I enjoy building end-to-end systems, not only isolated modules.',
  },
  {
    id: 'q19',
    category: 'communication' as const,
    question: 'I write clear documentation or notes for my work.',
  },
  {
    id: 'q20',
    category: 'leadership' as const,
    question: 'I am comfortable making decisions under pressure and uncertainty.',
  },
  {
    id: 'q21',
    category: 'creative' as const,
    question: 'I can suggest alternative solutions when the first approach fails.',
  },
  {
    id: 'q22',
    category: 'collaboration' as const,
    question: 'I resolve conflicts in teams without harming delivery speed.',
  },
  {
    id: 'q23',
    category: 'adaptability' as const,
    question: 'I stay productive even when I am asked to switch domains quickly.',
  },
  {
    id: 'q24',
    category: 'business' as const,
    question: 'I consider company goals and hiring trends while choosing what to learn.',
  },
];

export const availableSkills = [
  'Python', 'JavaScript', 'React', 'Node.js', 'SQL', 'Machine Learning',
  'Data Analysis', 'UI/UX Design', 'Project Management', 'Communication',
  'Leadership', 'Problem Solving', 'Critical Thinking', 'Teamwork',
  'Java', 'C++', 'AWS', 'Docker', 'Git', 'Agile',
];

export const availableInterests = [
  'Artificial Intelligence', 'Web Development', 'Mobile Apps', 'Data Science',
  'Cybersecurity', 'Cloud Computing', 'Game Development', 'Blockchain',
  'Product Management', 'UX Research', 'DevOps', 'Machine Learning',
];

export const mockCareerRecommendations: CareerRecommendation[] = [
  {
    id: 'career-1',
    title: 'Full Stack Developer',
    description: 'Build complete web applications from frontend to backend, creating seamless user experiences.',
    matchScore: 92,
    skillReadinessScore: 78,
    reasoning: [
      'Strong match with your technical aptitude score (4.5/5)',
      'Your JavaScript and React skills align perfectly',
      'Interest in Web Development directly correlates',
      'Problem-solving abilities indicate strong debugging potential',
    ],
    requiredSkills: ['JavaScript', 'React', 'Node.js', 'SQL', 'Git', 'API Design'],
    matchedSkills: ['JavaScript', 'React', 'Node.js', 'Git'],
    gapSkills: ['SQL', 'API Design'],
    averageSalary: '₹8-15 LPA',
    growthOutlook: 'High',
    icon: '💻',
  },
  {
    id: 'career-2',
    title: 'Data Scientist',
    description: 'Transform raw data into actionable insights using statistical analysis and machine learning.',
    matchScore: 87,
    skillReadinessScore: 65,
    reasoning: [
      'High analytical aptitude score (4.2/5) is crucial for this role',
      'Python programming skills provide a strong foundation',
      'Interest in Data Science and AI aligns well',
      'Critical thinking abilities support hypothesis testing',
    ],
    requiredSkills: ['Python', 'Machine Learning', 'SQL', 'Statistics', 'Data Visualization', 'TensorFlow'],
    matchedSkills: ['Python', 'Machine Learning', 'SQL'],
    gapSkills: ['Statistics', 'Data Visualization', 'TensorFlow'],
    averageSalary: '₹10-20 LPA',
    growthOutlook: 'High',
    icon: '📊',
  },
  {
    id: 'career-3',
    title: 'Product Manager',
    description: 'Lead product strategy and development, bridging business goals with user needs.',
    matchScore: 81,
    skillReadinessScore: 72,
    reasoning: [
      'Strong leadership aptitude (4.0/5) essential for team coordination',
      'Communication skills support stakeholder management',
      'Technical background enables effective developer collaboration',
      'Problem-solving aligns with product decision-making',
    ],
    requiredSkills: ['Product Strategy', 'Agile', 'Communication', 'Data Analysis', 'User Research', 'Roadmapping'],
    matchedSkills: ['Agile', 'Communication', 'Data Analysis'],
    gapSkills: ['Product Strategy', 'User Research', 'Roadmapping'],
    averageSalary: '₹12-25 LPA',
    growthOutlook: 'High',
    icon: '🚀',
  },
];

export const mockJobOpportunities: JobOpportunity[] = [
  {
    id: 'job-1',
    title: 'Junior Full Stack Developer',
    company: 'TechCorp India',
    location: 'Bangalore, India',
    type: 'Full-time',
    salary: '₹6-8 LPA',
    requiredSkills: ['React', 'Node.js', 'MongoDB', 'Git'],
    matchScore: 88,
    postedDate: '2 days ago',
    applyUrl: '#',
    logo: '🏢',
  },
  {
    id: 'job-2',
    title: 'Frontend Developer Intern',
    company: 'StartupXYZ',
    location: 'Remote',
    type: 'Internship',
    salary: '₹25,000/month',
    requiredSkills: ['React', 'JavaScript', 'CSS', 'TypeScript'],
    matchScore: 92,
    postedDate: '1 day ago',
    applyUrl: '#',
    logo: '🚀',
  },
  {
    id: 'job-3',
    title: 'Data Analyst',
    company: 'Analytics Pro',
    location: 'Hyderabad, India',
    type: 'Full-time',
    salary: '₹5-7 LPA',
    requiredSkills: ['Python', 'SQL', 'Excel', 'Tableau'],
    matchScore: 75,
    postedDate: '3 days ago',
    applyUrl: '#',
    logo: '📈',
  },
  {
    id: 'job-4',
    title: 'Software Engineer',
    company: 'MegaTech Solutions',
    location: 'Pune, India',
    type: 'Full-time',
    salary: '₹8-12 LPA',
    requiredSkills: ['Java', 'Spring Boot', 'AWS', 'Microservices'],
    matchScore: 68,
    postedDate: '5 days ago',
    applyUrl: '#',
    logo: '💼',
  },
  {
    id: 'job-5',
    title: 'ML Engineer Intern',
    company: 'AI Innovations',
    location: 'Mumbai, India',
    type: 'Internship',
    salary: '₹30,000/month',
    requiredSkills: ['Python', 'TensorFlow', 'Machine Learning', 'Deep Learning'],
    matchScore: 71,
    postedDate: '1 week ago',
    applyUrl: '#',
    logo: '🤖',
  },
];

export const generateRoadmap = (careerTitle: string): RoadmapMilestone[] => {
  const roadmaps: Record<string, RoadmapMilestone[]> = {
    'Full Stack Developer': [
      {
        id: 'fs-0',
        year: 1,
        semester: 1,
        title: 'Programming Basics',
        description: 'Build a strong foundation in programming and problem solving',
        importance: 5,
        skills: ['Programming Fundamentals', 'Problem Solving', 'Git Basics'],
        courses: [
          {
            title: 'Programming for Everybody',
            provider: 'Coursera',
            url: 'https://www.coursera.org/specializations/python',
            level: 'Beginner',
            duration: '18 hrs',
          },
          {
            title: 'CS50x',
            provider: 'edX',
            url: 'https://www.edx.org/course/cs50s-introduction-to-computer-science',
            level: 'Beginner',
            duration: '25 hrs',
          },
        ],
        projects: ['CLI Calculator', 'Basic Problem-Solving Tracker'],
        completed: false,
      },
      {
        id: 'fs-0-2',
        year: 1,
        semester: 2,
        title: 'Web Basics',
        description: 'Learn the building blocks of the web and basic scripting',
        importance: 4,
        skills: ['HTML', 'CSS', 'JavaScript Basics'],
        courses: [
          {
            title: 'HTML, CSS, and Javascript for Web Developers',
            provider: 'Coursera',
            url: 'https://www.coursera.org/learn/html-css-javascript-for-web-developers',
            level: 'Beginner',
            duration: '20 hrs',
          },
          {
            title: 'JavaScript Basics',
            provider: 'Udemy',
            url: 'https://www.udemy.com/course/the-complete-javascript-course',
            level: 'Beginner',
            duration: '10 hrs',
          },
        ],
        projects: ['Personal Portfolio v1', 'Landing Page Clone'],
        completed: false,
      },
      {
        id: 'fs-0-3',
        year: 2,
        semester: 1,
        title: 'Core CS & Tools',
        description: 'Strengthen CS fundamentals and developer tooling',
        importance: 3,
        skills: ['Data Structures', 'Algorithms', 'Git & GitHub'],
        courses: [
          {
            title: 'Data Structures and Algorithms',
            provider: 'Udemy',
            url: 'https://www.udemy.com/course/data-structures-and-algorithms-bootcamp-in-python',
            level: 'Intermediate',
            duration: '22 hrs',
          },
          {
            title: 'Git Complete',
            provider: 'Udemy',
            url: 'https://www.udemy.com/course/git-complete',
            level: 'Beginner',
            duration: '8 hrs',
          },
        ],
        projects: ['DSA Practice Tracker', 'GitHub Portfolio Setup'],
        completed: false,
      },
      {
        id: 'fs-0-4',
        year: 2,
        semester: 2,
        title: 'Frontend Foundations',
        description: 'Build responsive UI and learn modern JS patterns',
        importance: 3,
        skills: ['Advanced JavaScript', 'Responsive Design', 'APIs'],
        courses: [
          {
            title: 'Frontend Developer Career Path',
            provider: 'Scrimba',
            url: 'https://scrimba.com/learn/frontend',
            level: 'Intermediate',
            duration: '20 hrs',
          },
          {
            title: 'Responsive Web Design',
            provider: 'freeCodeCamp',
            url: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
            level: 'Beginner',
            duration: '15 hrs',
          },
        ],
        projects: ['Responsive Blog UI', 'API-driven Dashboard'],
        completed: false,
      },
      {
        id: 'fs-1',
        year: 3,
        semester: 1,
        title: 'Foundation Building',
        description: 'Master core web technologies and version control',
        importance: 5,
        skills: ['HTML/CSS', 'JavaScript ES6+', 'Git & GitHub'],
        courses: [
          {
            title: 'Web Development Fundamentals',
            provider: 'Coursera',
            url: 'https://www.coursera.org/learn/web-development',
            level: 'Beginner',
            duration: '20 hrs',
          },
          {
            title: 'JavaScript Deep Dive',
            provider: 'Udemy',
            url: 'https://www.udemy.com/course/javascript-the-complete-guide',
            level: 'Intermediate',
            duration: '24 hrs',
          },
        ],
        projects: ['Personal Portfolio Website', 'To-Do App with Local Storage'],
        completed: false,
      },
      {
        id: 'fs-2',
        year: 3,
        semester: 2,
        title: 'Frontend Mastery',
        description: 'Learn React and modern frontend development',
        importance: 5,
        skills: ['React.js', 'State Management', 'API Integration'],
        courses: [
          {
            title: 'React Complete Guide',
            provider: 'Udemy',
            url: 'https://www.udemy.com/course/react-the-complete-guide-incl-redux',
            level: 'Intermediate',
            duration: '40 hrs',
          },
          {
            title: 'Redux Toolkit Essentials',
            provider: 'YouTube',
            url: 'https://www.youtube.com/watch?v=9zySeP5vH9c',
            level: 'Intermediate',
            duration: '3 hrs',
          },
        ],
        projects: ['E-commerce Frontend', 'Weather Dashboard App'],
        internships: ['Frontend Developer Intern'],
        completed: false,
      },
      {
        id: 'fs-3',
        year: 4,
        semester: 1,
        title: 'Backend Development',
        description: 'Build robust server-side applications',
        importance: 5,
        skills: ['Node.js', 'Express.js', 'MongoDB', 'REST APIs'],
        courses: [
          {
            title: 'Node.js Masterclass',
            provider: 'Udemy',
            url: 'https://www.udemy.com/course/the-complete-nodejs-developer-course-2',
            level: 'Intermediate',
            duration: '35 hrs',
          },
          {
            title: 'Database Design',
            provider: 'edX',
            url: 'https://www.edx.org/learn/database-design',
            level: 'Beginner',
            duration: '12 hrs',
          },
        ],
        projects: ['Blog Platform API', 'Authentication System'],
        certifications: ['MongoDB Developer Certification'],
        completed: false,
      },
      {
        id: 'fs-4',
        year: 4,
        semester: 2,
        title: 'Full Stack Integration & Placement',
        description: 'Combine skills and prepare for industry',
        importance: 5,
        skills: ['Docker', 'CI/CD', 'Cloud Deployment', 'System Design'],
        courses: [
          {
            title: 'DevOps Fundamentals',
            provider: 'Coursera',
            url: 'https://www.coursera.org/learn/devops-culture-and-mindset',
            level: 'Intermediate',
            duration: '16 hrs',
          },
          {
            title: 'System Design Interview Prep',
            provider: 'YouTube',
            url: 'https://www.youtube.com/watch?v=MbjObHmDbZo',
            level: 'Advanced',
            duration: '4 hrs',
          },
        ],
        projects: ['Complete SaaS Application', 'Open Source Contribution'],
        internships: ['Full Stack Developer Intern'],
        certifications: ['AWS Cloud Practitioner'],
        completed: false,
      },
    ],
    'Data Scientist': [
      {
        id: 'ds-0',
        year: 1,
        semester: 1,
        title: 'Math & Programming Basics',
        description: 'Strengthen math fundamentals and basic programming',
        importance: 5,
        skills: ['Python Basics', 'Algebra', 'Problem Solving'],
        courses: [
          {
            title: 'Python for Everybody',
            provider: 'Coursera',
            url: 'https://www.coursera.org/specializations/python',
            level: 'Beginner',
            duration: '18 hrs',
          },
          {
            title: 'Khan Academy Algebra',
            provider: 'Khan Academy',
            url: 'https://www.khanacademy.org/math/algebra',
            level: 'Beginner',
            duration: '10 hrs',
          },
        ],
        projects: ['Basic Data Cleaning Script', 'Math Practice Log'],
        completed: false,
      },
      {
        id: 'ds-0-2',
        year: 1,
        semester: 2,
        title: 'Data Foundations',
        description: 'Learn basic data handling and visualization',
        importance: 4,
        skills: ['Python', 'Pandas Basics', 'Data Visualization'],
        courses: [
          {
            title: 'Data Analysis with Python',
            provider: 'freeCodeCamp',
            url: 'https://www.freecodecamp.org/learn/data-analysis-with-python/',
            level: 'Beginner',
            duration: '20 hrs',
          },
          {
            title: 'Data Visualization',
            provider: 'Kaggle',
            url: 'https://www.kaggle.com/learn/data-visualization',
            level: 'Beginner',
            duration: '6 hrs',
          },
        ],
        projects: ['Simple EDA Notebook', 'Charting Mini Project'],
        completed: false,
      },
      {
        id: 'ds-0-3',
        year: 2,
        semester: 1,
        title: 'Statistics & SQL',
        description: 'Build statistical intuition and SQL foundations',
        importance: 4,
        skills: ['Statistics', 'SQL Basics', 'Data Wrangling'],
        courses: [
          {
            title: 'Statistics Fundamentals',
            provider: 'Khan Academy',
            url: 'https://www.khanacademy.org/math/statistics-probability',
            level: 'Beginner',
            duration: '12 hrs',
          },
          {
            title: 'SQL for Data Science',
            provider: 'Coursera',
            url: 'https://www.coursera.org/learn/sql-for-data-science',
            level: 'Beginner',
            duration: '15 hrs',
          },
        ],
        projects: ['SQL Query Practice', 'Stats Summary Report'],
        completed: false,
      },
      {
        id: 'ds-0-4',
        year: 2,
        semester: 2,
        title: 'Applied Analytics',
        description: 'Work with real datasets and basic ML ideas',
        importance: 3,
        skills: ['Data Cleaning', 'Feature Basics', 'Modeling Concepts'],
        courses: [
          {
            title: 'Intro to Machine Learning',
            provider: 'Kaggle',
            url: 'https://www.kaggle.com/learn/intro-to-machine-learning',
            level: 'Beginner',
            duration: '6 hrs',
          },
          {
            title: 'Python Data Science Handbook',
            provider: 'O’Reilly',
            url: 'https://jakevdp.github.io/PythonDataScienceHandbook/',
            level: 'Intermediate',
            duration: '12 hrs',
          },
        ],
        projects: ['Kaggle Mini Project', 'Dataset Report'],
        completed: false,
      },
      {
        id: 'ds-1',
        year: 3,
        semester: 1,
        title: 'Programming & Statistics Foundation',
        description: 'Build strong Python and statistical analysis skills',
        importance: 5,
        skills: ['Python', 'NumPy', 'Pandas', 'Statistics'],
        courses: [
          {
            title: 'Python for Data Science',
            provider: 'Coursera',
            url: 'https://www.coursera.org/learn/python-for-applied-data-science-ai',
            level: 'Beginner',
            duration: '14 hrs',
          },
          {
            title: 'Statistics Fundamentals',
            provider: 'Khan Academy',
            url: 'https://www.khanacademy.org/math/statistics-probability',
            level: 'Beginner',
            duration: '12 hrs',
          },
        ],
        projects: ['Exploratory Data Analysis Project', 'Statistical Analysis Report'],
        completed: false,
      },
      {
        id: 'ds-2',
        year: 3,
        semester: 2,
        title: 'Machine Learning Fundamentals',
        description: 'Learn core ML algorithms and techniques',
        importance: 5,
        skills: ['Scikit-learn', 'Feature Engineering', 'Model Evaluation'],
        courses: [
          {
            title: 'Machine Learning A-Z',
            provider: 'Udemy',
            url: 'https://www.udemy.com/course/machinelearning',
            level: 'Intermediate',
            duration: '42 hrs',
          },
          {
            title: 'Feature Engineering Course',
            provider: 'Kaggle',
            url: 'https://www.kaggle.com/learn/feature-engineering',
            level: 'Intermediate',
            duration: '6 hrs',
          },
        ],
        projects: ['House Price Prediction', 'Customer Segmentation'],
        internships: ['Data Analyst Intern'],
        completed: false,
      },
      {
        id: 'ds-3',
        year: 4,
        semester: 1,
        title: 'Advanced ML & Deep Learning',
        description: 'Master neural networks and deep learning',
        importance: 5,
        skills: ['TensorFlow', 'PyTorch', 'NLP', 'Computer Vision'],
        courses: [
          {
            title: 'Deep Learning Specialization',
            provider: 'Coursera',
            url: 'https://www.coursera.org/specializations/deep-learning',
            level: 'Advanced',
            duration: '60 hrs',
          },
          {
            title: 'NLP with Transformers',
            provider: 'Hugging Face',
            url: 'https://huggingface.co/learn/nlp-course/chapter1/1',
            level: 'Advanced',
            duration: '10 hrs',
          },
        ],
        projects: ['Image Classification Model', 'Sentiment Analysis System'],
        certifications: ['TensorFlow Developer Certificate'],
        completed: false,
      },
      {
        id: 'ds-4',
        year: 4,
        semester: 2,
        title: 'Industry Projects & Placement',
        description: 'Real-world applications and interview prep',
        importance: 5,
        skills: ['MLOps', 'Model Deployment', 'A/B Testing', 'Big Data'],
        courses: [
          {
            title: 'MLOps Bootcamp',
            provider: 'Coursera',
            url: 'https://www.coursera.org/specializations/mlops-machine-learning-duke',
            level: 'Advanced',
            duration: '40 hrs',
          },
          {
            title: 'Data Science Interview Prep',
            provider: 'YouTube',
            url: 'https://www.youtube.com/watch?v=R7g0Qm8G2pA',
            level: 'Intermediate',
            duration: '3 hrs',
          },
        ],
        projects: ['End-to-End ML Pipeline', 'Kaggle Competition'],
        internships: ['Data Science Intern'],
        certifications: ['AWS ML Specialty'],
        completed: false,
      },
    ],
    'Product Manager': [
      {
        id: 'pm-0',
        year: 1,
        semester: 1,
        title: 'Business & Communication Basics',
        description: 'Build fundamentals in communication and business basics',
        importance: 4,
        skills: ['Communication', 'Business Basics', 'Presentation'],
        courses: [
          {
            title: 'Introduction to Business',
            provider: 'Coursera',
            url: 'https://www.coursera.org/specializations/wharton-business-foundations',
            level: 'Beginner',
            duration: '18 hrs',
          },
          {
            title: 'Communication Skills',
            provider: 'LinkedIn Learning',
            url: 'https://www.linkedin.com/learning/paths/communication-skills',
            level: 'Beginner',
            duration: '8 hrs',
          },
        ],
        projects: ['Product Review Write-up', 'Presentation Deck'],
        completed: false,
      },
      {
        id: 'pm-0-2',
        year: 1,
        semester: 2,
        title: 'User & Market Basics',
        description: 'Learn user needs and basic market research',
        importance: 4,
        skills: ['User Empathy', 'Market Research', 'Survey Design'],
        courses: [
          {
            title: 'Market Research',
            provider: 'edX',
            url: 'https://www.edx.org/learn/marketing',
            level: 'Beginner',
            duration: '10 hrs',
          },
          {
            title: 'Design Thinking',
            provider: 'Coursera',
            url: 'https://www.coursera.org/specializations/design-thinking-innovation',
            level: 'Beginner',
            duration: '14 hrs',
          },
        ],
        projects: ['User Interview Plan', 'Survey Report'],
        completed: false,
      },
      {
        id: 'pm-0-3',
        year: 2,
        semester: 1,
        title: 'Product & Agile Basics',
        description: 'Understand product lifecycle and agile practices',
        importance: 3,
        skills: ['Product Lifecycle', 'Agile Basics', 'User Stories'],
        courses: [
          {
            title: 'Agile Fundamentals',
            provider: 'edX',
            url: 'https://www.edx.org/learn/agile',
            level: 'Beginner',
            duration: '10 hrs',
          },
          {
            title: 'Introduction to Product Management',
            provider: 'Coursera',
            url: 'https://www.coursera.org/learn/uva-darden-product-management',
            level: 'Beginner',
            duration: '14 hrs',
          },
        ],
        projects: ['User Story Map', 'Product Brief'],
        completed: false,
      },
      {
        id: 'pm-0-4',
        year: 2,
        semester: 2,
        title: 'Analytics & UX Basics',
        description: 'Learn to interpret product data and UX principles',
        importance: 3,
        skills: ['Product Analytics', 'UX Basics', 'Experiment Design'],
        courses: [
          {
            title: 'Product Analytics',
            provider: 'Udacity',
            url: 'https://www.udacity.com/course/product-analytics--ud509',
            level: 'Intermediate',
            duration: '10 hrs',
          },
          {
            title: 'UX Research Methods',
            provider: 'Coursera',
            url: 'https://www.coursera.org/learn/ux-research',
            level: 'Intermediate',
            duration: '12 hrs',
          },
        ],
        projects: ['Analytics Dashboard Sketch', 'A/B Test Plan'],
        completed: false,
      },
      {
        id: 'pm-1',
        year: 3,
        semester: 1,
        title: 'Product Fundamentals',
        description: 'Understand product management basics and methodologies',
        importance: 5,
        skills: ['Product Thinking', 'Market Research', 'User Stories'],
        courses: [
          {
            title: 'Introduction to Product Management',
            provider: 'Coursera',
            url: 'https://www.coursera.org/learn/uva-darden-product-management',
            level: 'Beginner',
            duration: '14 hrs',
          },
          {
            title: 'Agile Fundamentals',
            provider: 'edX',
            url: 'https://www.edx.org/learn/agile',
            level: 'Beginner',
            duration: '10 hrs',
          },
        ],
        projects: ['Product Case Study Analysis', 'Feature Prioritization Exercise'],
        completed: false,
      },
      {
        id: 'pm-2',
        year: 3,
        semester: 2,
        title: 'User Research & Analytics',
        description: 'Learn to understand users and measure success',
        importance: 5,
        skills: ['User Interviews', 'Analytics Tools', 'A/B Testing'],
        courses: [
          {
            title: 'UX Research Methods',
            provider: 'Coursera',
            url: 'https://www.coursera.org/learn/ux-research',
            level: 'Intermediate',
            duration: '12 hrs',
          },
          {
            title: 'Product Analytics',
            provider: 'Udacity',
            url: 'https://www.udacity.com/course/product-analytics--ud509',
            level: 'Intermediate',
            duration: '10 hrs',
          },
        ],
        projects: ['User Research Project', 'Analytics Dashboard Setup'],
        internships: ['Product Intern'],
        completed: false,
      },
      {
        id: 'pm-3',
        year: 4,
        semester: 1,
        title: 'Product Strategy & Leadership',
        description: 'Develop strategic thinking and leadership skills',
        importance: 5,
        skills: ['Roadmapping', 'Stakeholder Management', 'Go-to-Market'],
        courses: [
          {
            title: 'Product Strategy',
            provider: 'Coursera',
            url: 'https://www.coursera.org/learn/product-strategy',
            level: 'Advanced',
            duration: '12 hrs',
          },
          {
            title: 'Leadership Skills',
            provider: 'LinkedIn Learning',
            url: 'https://www.linkedin.com/learning/paths/leadership-skills',
            level: 'Intermediate',
            duration: '8 hrs',
          },
        ],
        projects: ['Product Roadmap Creation', 'GTM Plan Development'],
        certifications: ['Product Management Certification'],
        completed: false,
      },
      {
        id: 'pm-4',
        year: 4,
        semester: 2,
        title: 'Industry Experience & Placement',
        description: 'Apply skills in real-world settings',
        importance: 5,
        skills: ['Cross-functional Leadership', 'Technical Communication', 'Data-Driven Decisions'],
        courses: [
          {
            title: 'PM Interview Prep',
            provider: 'YouTube',
            url: 'https://www.youtube.com/watch?v=6P2xk1V0Jx4',
            level: 'Intermediate',
            duration: '3 hrs',
          },
          {
            title: 'Advanced Product Management',
            provider: 'edX',
            url: 'https://www.edx.org/learn/product-management',
            level: 'Advanced',
            duration: '16 hrs',
          },
        ],
        projects: ['Full Product Lifecycle Project', 'Startup MVP'],
        internships: ['Associate Product Manager Intern'],
        completed: false,
      },
    ],
  };

  return roadmaps[careerTitle] || roadmaps['Full Stack Developer'];
};

export const mockProgressAnalytics: ProgressAnalytics = {
  overallReadiness: 72,
  skillProgress: [
    { skill: 'JavaScript', current: 85, target: 90 },
    { skill: 'React', current: 78, target: 85 },
    { skill: 'Node.js', current: 65, target: 80 },
    { skill: 'SQL', current: 50, target: 75 },
    { skill: 'Git', current: 90, target: 90 },
  ],
  completedMilestones: 2,
  totalMilestones: 4,
  weeklyProgress: [
    { week: 'Week 1', progress: 15 },
    { week: 'Week 2', progress: 28 },
    { week: 'Week 3', progress: 42 },
    { week: 'Week 4', progress: 55 },
    { week: 'Week 5', progress: 65 },
    { week: 'Week 6', progress: 72 },
  ],
};
